### PR TITLE
Delete wikiteam/launcher.py

### PR DESCRIPTION
**Pull request by robkam**
File is still in use.

### CODE REVIEW

**Comment by randomnetcat** [comment]
Again, why delete this? It should be working and I use it (although admittedly my deployment is not up to date).

**Comment by randomnetcat** [comment]
Oh oops wrong repo.

**Review by randomnetcat — APPROVED** [review]

**Comment by robkam** [comment]
Uploader.py and launcher.py are in the repo _upstream-to-sort_. They shouldn't be. They're still useful and properly exist in the repo  _mediawiki-dump-generator_.

**Comment by elsiehupp** [comment]
The entire `wikiteam` directory can be removed from this repo, since the files in it didn't end up getting removed from the other one.

**Comment by robkam** [comment]
Done that with #11

**Pull request closed without merging**
